project_id = "rrvraugvigylkdpstwsl"

[functions.summarize-patent]
verify_jwt = false

[functions.fetch-patent]
verify_jwt = false

[functions.search-patents]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false

[functions.rda-latest-patents]
verify_jwt = false

[functions.manage-featured-patents]
verify_jwt = false