// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-patents.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-patents.ts
var search_patents_default = defineTool({
  name: "search_patents",
  title: "Search agricultural patents",
  description: "Search Korean agricultural patents from KIPRIS by keyword, inventor, or patent number. Returns a ranked list with titles, applicants, and relevance scores.",
  inputSchema: {
    query: z.string().min(1).max(200).describe("Search keyword, inventor name, or patent number."),
    count: z.number().int().min(1).max(50).optional().describe("Maximum number of results (default 20)."),
    source: z.enum(["all", "rda", "kipris"]).optional().describe("Source filter: all (default), rda, or kipris.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, count, source }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("search-patents", {
      body: {
        keyword: query,
        count: count ?? 20,
        source: source ?? "all"
      }
    });
    if (error) {
      throw new ToolError(`Patent search failed: ${error.message}`);
    }
    const result = data;
    if (!result.success || result.error) {
      throw new ToolError(result.error || "Patent search returned no results.");
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${result.total ?? result.results?.length ?? 0} patents for "${query}".`
        }
      ],
      structuredContent: {
        query,
        total: result.total ?? result.results?.length ?? 0,
        patents: result.results ?? []
      }
    };
  }
});

// src/lib/mcp/tools/fetch-patent.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var fetch_patent_default = defineTool2({
  name: "fetch_patent",
  title: "Fetch patent details",
  description: "Retrieve detailed bibliographic data, claims, abstract, and representative drawing for a Korean patent by its patent number.",
  inputSchema: {
    patent_number: z2.string().min(5).max(30).describe("Korean patent number, e.g. 10-2017-0149000.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patent_number }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("fetch-patent", {
      body: { patentNumber: patent_number }
    });
    if (error) {
      throw new ToolError2(`Failed to fetch patent ${patent_number}: ${error.message}`);
    }
    const result = data;
    if (!result.success || !result.data) {
      throw new ToolError2(result.error || `Patent ${patent_number} not found.`);
    }
    return {
      content: [
        { type: "text", text: `Retrieved details for ${patent_number}: ${result.data.titleKo || result.data.title || ""}` }
      ],
      structuredContent: { patentNumber: patent_number, patent: result.data }
    };
  }
});

// src/lib/mcp/tools/summarize-patent.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var summarize_patent_default = defineTool3({
  name: "summarize_patent",
  title: "Summarize patent in plain language",
  description: "Generate an easy-to-read Korean summary of a patent, including core technology, problem solved, key means, quantitative effects, and commercialization fields.",
  inputSchema: {
    patent_number: z3.string().min(5).max(30).describe("Korean patent number, e.g. 10-2017-0149000.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ patent_number }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("summarize-patent", {
      body: { patentNumber: patent_number }
    });
    if (error) {
      throw new ToolError3(`Summary failed for ${patent_number}: ${error.message}`);
    }
    const result = data;
    if (!result.success || !result.summary) {
      throw new ToolError3(result.error || "Could not generate summary.");
    }
    return {
      content: [{ type: "text", text: result.summary }]
    };
  }
});

// src/lib/mcp/tools/analyze-commercialization.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var analyze_commercialization_default = defineTool4({
  name: "analyze_commercialization",
  title: "Analyze commercialization potential",
  description: "Evaluate a patent's technology readiness, marketability, and business viability, returning scores, grade, and strategic recommendations.",
  inputSchema: {
    patent_number: z4.string().min(5).max(30).describe("Korean patent number, e.g. 10-2017-0149000.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ patent_number }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("analyze-commercialization", {
      body: { patentNumber: patent_number }
    });
    if (error) {
      throw new ToolError4(`Commercialization analysis failed for ${patent_number}: ${error.message}`);
    }
    const result = data;
    if (!result.success || !result.analysis) {
      throw new ToolError4(result.error || "Could not analyze commercialization potential.");
    }
    return {
      content: [
        {
          type: "text",
          text: `Commercialization analysis for ${patent_number}: total score ${result.analysis.totalScore ?? "N/A"}, grade ${result.analysis.grade ?? "N/A"}.`
        }
      ],
      structuredContent: { patentNumber: patent_number, analysis: result.analysis }
    };
  }
});

// src/lib/mcp/tools/recommend-similar-patents.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var recommend_similar_patents_default = defineTool5({
  name: "recommend_similar_patents",
  title: "Recommend similar patents",
  description: "Find semantically similar Korean agricultural patents to a given patent number, with matching reason and keyword overlap.",
  inputSchema: {
    patent_number: z5.string().min(5).max(30).describe("Korean patent number, e.g. 10-2017-0149000."),
    count: z5.number().int().min(1).max(20).optional().describe("Maximum number of recommendations (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ patent_number, count }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("recommend-similar-patents", {
      body: { patentNumber: patent_number, count: count ?? 10 }
    });
    if (error) {
      throw new ToolError5(`Recommendation failed for ${patent_number}: ${error.message}`);
    }
    const result = data;
    if (!result.success || !result.recommendations) {
      throw new ToolError5(result.error || "Could not generate recommendations.");
    }
    return {
      content: [
        {
          type: "text",
          text: `Found ${result.recommendations.length} similar patents for ${patent_number}.`
        }
      ],
      structuredContent: {
        patentNumber: patent_number,
        recommendations: result.recommendations
      }
    };
  }
});

// src/lib/mcp/tools/analyze-regulations.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var analyze_regulations_default = defineTool6({
  name: "analyze_regulations",
  title: "Analyze regulations for commercialization",
  description: "Identify Korean laws and regulations that may apply when commercializing a technology, based on the patent's technical field.",
  inputSchema: {
    patent_number: z6.string().min(5).max(30).describe("Korean patent number, e.g. 10-2017-0149000."),
    tech_field: z6.string().max(100).optional().describe("Optional technical field override (e.g. 'functional food', 'agricultural machinery').")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ patent_number, tech_field }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.functions.invoke("analyze-regulations", {
      body: { patentNumber: patent_number, techField: tech_field }
    });
    if (error) {
      throw new ToolError6(`Regulation analysis failed for ${patent_number}: ${error.message}`);
    }
    const result = data;
    if (!result.success || !result.regulations) {
      throw new ToolError6(result.error || "Could not analyze regulations.");
    }
    return {
      content: [
        {
          type: "text",
          text: result.summary || `Identified ${result.regulations.length} potentially relevant regulations for ${patent_number}.`
        }
      ],
      structuredContent: {
        patentNumber: patent_number,
        regulations: result.regulations
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rrvraugvigylkdpstwsl";
var mcp_default = defineMcp({
  name: "ai-gisulbunseog",
  title: "AI \uAE30\uC220\uBD84\uC11D \uC11C\uBE44\uC2A4",
  version: "1.0.0",
  instructions: "Korean agricultural patent analysis tools. Use search_patents to find patents, fetch_patent to retrieve details, summarize_patent for plain-language summaries, analyze_commercialization for scoring and strategy, recommend_similar_patents for related patents, and analyze_regulations for applicable Korean laws.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_patents_default, fetch_patent_default, summarize_patent_default, analyze_commercialization_default, recommend_similar_patents_default, analyze_regulations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
